// web/src/lib/components/dashboard/stats-card.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import type { Component } from 'svelte'
  import Card from '$lib/components/ui/card.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import CardHeader from '$lib/components/ui/card-header.svelte'
  import CardTitle from '$lib/components/ui/card-title.svelte'

  interface Props {
    title: string
    value: string | number
    description?: string
    icon: Component
    trend?: { value: number; isPositive: boolean }
    class?: string
  }

  let { title, value, description, icon: Icon, trend, class: className = '' }: Props = $props()
</script>

<Card class={cn(className)}>
  <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
    <CardTitle class="text-sm font-medium">{title}</CardTitle>
    <Icon class="h-4 w-4 text-muted-foreground" />
  </CardHeader>
  <CardContent>
    <div class="text-2xl font-bold">{value}</div>
    {#if description}
      <p class="text-xs text-muted-foreground mt-1">{description}</p>
    {/if}
    {#if trend}
      <p class={cn('text-xs mt-1', trend.isPositive ? 'text-green-600' : 'text-red-600')}>
        {trend.isPositive ? '+' : ''}{trend.value}% o'tgan oydan
      </p>
    {/if}
  </CardContent>
</Card>

// frontend/src/components/dashboard/stats-card.tsx
"use client"

import { cn } from "@/lib/utils"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { LucideIcon } from "lucide-react"

interface StatsCardProps {
  title: string
  value: string | number
  description?: string
  icon?: LucideIcon
  trend?: {
    value: number
    isPositive: boolean
  }
  className?: string
}

export function StatsCard({
  title,
  value,
  description,
  icon: Icon,
  trend,
  className,
}: StatsCardProps) {
  return (
    <Card className={cn("", className)}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          {title}
        </CardTitle>
        {Icon && <Icon className="h-4 w-4 text-muted-foreground" />}
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{value}</div>
        {description && (
          <p className="text-xs text-muted-foreground">{description}</p>
        )}
        {trend && (
          <p
            className={cn(
              "text-xs",
              trend.isPositive ? "text-green-600" : "text-red-600"
            )}
          >
            {trend.isPositive ? "+" : "-"}
            {trend.value}% o'tgan oyga nisbatan
          </p>
        )}
      </CardContent>
    </Card>
  )
}
