// frontend/src/components/ui/modal.tsx
"use client"

import * as React from "react"
import { cn } from "@/lib/utils"
import { X } from "lucide-react"

interface ModalProps {
  isOpen: boolean
  onClose: () => void
  title?: string
  description?: string
  children: React.ReactNode
  className?: string
  size?: "sm" | "md" | "lg" | "xl" | "full"
}

const sizeClasses = {
  sm: "max-w-sm",
  md: "max-w-md",
  lg: "max-w-lg",
  xl: "max-w-xl",
  full: "max-w-4xl",
}

export function Modal({
  isOpen,
  onClose,
  title,
  description,
  children,
  className,
  size = "md",
}: ModalProps) {
  React.useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose()
      }
    }

    if (isOpen) {
      document.addEventListener("keydown", handleEscape)
      document.body.style.overflow = "hidden"
    }

    return () => {
      document.removeEventListener("keydown", handleEscape)
      document.body.style.overflow = "unset"
    }
  }, [isOpen, onClose])

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 transition-opacity"
        onClick={onClose}
      />

      {/* Modal */}
      <div
        className={cn(
          "relative z-50 w-full rounded-lg bg-background p-6 shadow-lg animate-in fade-in-0 zoom-in-95",
          sizeClasses[size],
          className
        )}
      >
        {/* Header */}
        {(title || description) && (
          <div className="mb-4">
            {title && (
              <h2 className="text-lg font-semibold">{title}</h2>
            )}
            {description && (
              <p className="text-sm text-muted-foreground">{description}</p>
            )}
          </div>
        )}

        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          <X className="h-4 w-4" />
          <span className="sr-only">Yopish</span>
        </button>

        {/* Content */}
        <div>{children}</div>
      </div>
    </div>
  )
}

// Modal Footer for action buttons
interface ModalFooterProps {
  children: React.ReactNode
  className?: string
}

export function ModalFooter({ children, className }: ModalFooterProps) {
  return (
    <div
      className={cn(
        "mt-6 flex items-center justify-end gap-2",
        className
      )}
    >
      {children}
    </div>
  )
}

// web/src/lib/components/ui/modal.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import { X } from 'lucide-svelte'
  import type { Snippet } from 'svelte'

  interface Props {
    isOpen: boolean
    onClose: () => void
    title?: string
    description?: string
    size?: 'sm' | 'md' | 'lg' | 'xl' | 'full'
    class?: string
    children?: Snippet
  }

  let {
    isOpen,
    onClose,
    title,
    description,
    size = 'md',
    class: className = '',
    children,
  }: Props = $props()

  const sizeClasses: Record<string, string> = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-xl',
    full: 'max-w-4xl',
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose()
  }

  $effect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden'
      document.addEventListener('keydown', handleKeydown)
    } else {
      document.body.style.overflow = ''
      document.removeEventListener('keydown', handleKeydown)
    }
    return () => {
      document.body.style.overflow = ''
      document.removeEventListener('keydown', handleKeydown)
    }
  })
</script>

{#if isOpen}
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <!-- Backdrop -->
    <div
      class="fixed inset-0 bg-black/50 transition-opacity"
      onclick={onClose}
      role="presentation"
    ></div>

    <!-- Modal panel -->
    <div
      class={cn(
        'relative z-50 w-full rounded-lg bg-background p-6 shadow-lg',
        sizeClasses[size],
        className,
      )}
      role="dialog"
      aria-modal="true"
    >
      {#if title || description}
        <div class="mb-4 pr-6">
          {#if title}
            <h2 class="text-lg font-semibold">{title}</h2>
          {/if}
          {#if description}
            <p class="text-sm text-muted-foreground">{description}</p>
          {/if}
        </div>
      {/if}

      <button
        type="button"
        class="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        onclick={onClose}
      >
        <X class="h-4 w-4" />
        <span class="sr-only">Yopish</span>
      </button>

      {#if children}{@render children()}{/if}
    </div>
  </div>
{/if}
