// frontend/src/components/ui/pagination.tsx
"use client"

import * as React from "react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "lucide-react"

interface PaginationProps {
  currentPage: number
  totalPages: number
  onPageChange: (page: number) => void
  siblingCount?: number
  className?: string
}

export function Pagination({
  currentPage,
  totalPages,
  onPageChange,
  siblingCount = 1,
  className,
}: PaginationProps) {
  const range = (start: number, end: number) => {
    const length = end - start + 1
    return Array.from({ length }, (_, idx) => idx + start)
  }

  const paginationRange = React.useMemo(() => {
    const totalPageNumbers = siblingCount + 5

    if (totalPageNumbers >= totalPages) {
      return range(1, totalPages)
    }

    const leftSiblingIndex = Math.max(currentPage - siblingCount, 1)
    const rightSiblingIndex = Math.min(currentPage + siblingCount, totalPages)

    const shouldShowLeftDots = leftSiblingIndex > 2
    const shouldShowRightDots = rightSiblingIndex < totalPages - 2

    const firstPageIndex = 1
    const lastPageIndex = totalPages

    if (!shouldShowLeftDots && shouldShowRightDots) {
      const leftItemCount = 3 + 2 * siblingCount
      const leftRange = range(1, leftItemCount)

      return [...leftRange, "...", totalPages]
    }

    if (shouldShowLeftDots && !shouldShowRightDots) {
      const rightItemCount = 3 + 2 * siblingCount
      const rightRange = range(totalPages - rightItemCount + 1, totalPages)

      return [firstPageIndex, "...", ...rightRange]
    }

    if (shouldShowLeftDots && shouldShowRightDots) {
      const middleRange = range(leftSiblingIndex, rightSiblingIndex)

      return [firstPageIndex, "...", ...middleRange, "...", lastPageIndex]
    }

    return range(1, totalPages)
  }, [totalPages, siblingCount, currentPage])

  if (totalPages <= 1) return null

  return (
    <div className={cn("flex items-center justify-center gap-1", className)}>
      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(1)}
        disabled={currentPage === 1}
        className="hidden sm:flex"
      >
        <ChevronsLeft className="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(currentPage - 1)}
        disabled={currentPage === 1}
      >
        <ChevronLeft className="h-4 w-4" />
      </Button>

      {paginationRange.map((pageNumber, index) => {
        if (pageNumber === "...") {
          return (
            <span
              key={`dots-${index}`}
              className="px-2 text-muted-foreground"
            >
              ...
            </span>
          )
        }

        return (
          <Button
            key={pageNumber}
            variant={currentPage === pageNumber ? "default" : "outline"}
            size="icon"
            onClick={() => onPageChange(pageNumber as number)}
            className={cn(
              currentPage === pageNumber && "bg-primary text-primary-foreground"
            )}
          >
            {pageNumber}
          </Button>
        )
      })}

      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(currentPage + 1)}
        disabled={currentPage === totalPages}
      >
        <ChevronRight className="h-4 w-4" />
      </Button>
      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(totalPages)}
        disabled={currentPage === totalPages}
        className="hidden sm:flex"
      >
        <ChevronsRight className="h-4 w-4" />
      </Button>
    </div>
  )
}

interface PaginationInfoProps {
  currentPage: number
  pageSize: number
  totalItems: number
  className?: string
}

export function PaginationInfo({
  currentPage,
  pageSize,
  totalItems,
  className,
}: PaginationInfoProps) {
  const startItem = (currentPage - 1) * pageSize + 1
  const endItem = Math.min(currentPage * pageSize, totalItems)

  return (
    <p className={cn("text-sm text-muted-foreground", className)}>
      {startItem}-{endItem} / {totalItems} ta
    </p>
  )
}

interface PageSizeSelectorProps {
  pageSize: number
  options?: number[]
  onPageSizeChange: (size: number) => void
  className?: string
}

export function PageSizeSelector({
  pageSize,
  options = [10, 20, 50, 100],
  onPageSizeChange,
  className,
}: PageSizeSelectorProps) {
  return (
    <div className={cn("flex items-center gap-2", className)}>
      <span className="text-sm text-muted-foreground">Sahifada:</span>
      <select
        value={pageSize}
        onChange={(e) => onPageSizeChange(Number(e.target.value))}
        className="h-8 rounded-md border bg-background px-2 text-sm"
      >
        {options.map((option) => (
          <option key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    </div>
  )
}

// web/src/lib/components/ui/pagination.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-svelte'

  interface Props {
    currentPage: number
    totalPages: number
    onPageChange: (page: number) => void
    siblingCount?: number
    class?: string
  }

  let {
    currentPage,
    totalPages,
    onPageChange,
    siblingCount = 1,
    class: className = '',
  }: Props = $props()

  function range(start: number, end: number): number[] {
    return Array.from({ length: end - start + 1 }, (_, i) => i + start)
  }

  const paginationRange = $derived.by(() => {
    const totalPageNumbers = siblingCount + 5
    if (totalPageNumbers >= totalPages) return range(1, totalPages)

    const leftSiblingIndex = Math.max(currentPage - siblingCount, 1)
    const rightSiblingIndex = Math.min(currentPage + siblingCount, totalPages)
    const shouldShowLeftDots = leftSiblingIndex > 2
    const shouldShowRightDots = rightSiblingIndex < totalPages - 2

    if (!shouldShowLeftDots && shouldShowRightDots) {
      return [...range(1, 3 + 2 * siblingCount), '...', totalPages]
    }
    if (shouldShowLeftDots && !shouldShowRightDots) {
      return [1, '...', ...range(totalPages - (3 + 2 * siblingCount) + 1, totalPages)]
    }
    if (shouldShowLeftDots && shouldShowRightDots) {
      return [1, '...', ...range(leftSiblingIndex, rightSiblingIndex), '...', totalPages]
    }
    return range(1, totalPages)
  })

  const btnBase =
    'inline-flex h-9 w-9 items-center justify-center rounded-md border text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
</script>

{#if totalPages > 1}
  <div class={cn('flex items-center justify-center gap-1', className)}>
    <button
      type="button"
      class="{btnBase} hidden border-input bg-background hover:bg-accent sm:inline-flex"
      disabled={currentPage === 1}
      onclick={() => onPageChange(1)}
    >
      <ChevronsLeft class="h-4 w-4" />
    </button>
    <button
      type="button"
      class="{btnBase} border-input bg-background hover:bg-accent"
      disabled={currentPage === 1}
      onclick={() => onPageChange(currentPage - 1)}
    >
      <ChevronLeft class="h-4 w-4" />
    </button>

    {#each paginationRange as page, i}
      {#if page === '...'}
        <span class="px-2 text-muted-foreground">...</span>
      {:else}
        <button
          type="button"
          class={cn(
            btnBase,
            currentPage === page
              ? 'border-primary bg-primary text-primary-foreground'
              : 'border-input bg-background hover:bg-accent',
          )}
          onclick={() => onPageChange(page as number)}
        >
          {page}
        </button>
      {/if}
    {/each}

    <button
      type="button"
      class="{btnBase} border-input bg-background hover:bg-accent"
      disabled={currentPage === totalPages}
      onclick={() => onPageChange(currentPage + 1)}
    >
      <ChevronRight class="h-4 w-4" />
    </button>
    <button
      type="button"
      class="{btnBase} hidden border-input bg-background hover:bg-accent sm:inline-flex"
      disabled={currentPage === totalPages}
      onclick={() => onPageChange(totalPages)}
    >
      <ChevronsRight class="h-4 w-4" />
    </button>
  </div>
{/if}
