// frontend/src/components/ui/switch.tsx
"use client"

import * as React from "react"
import { cn } from "@/lib/utils"

interface SwitchProps {
  checked?: boolean
  onCheckedChange?: (checked: boolean) => void
  disabled?: boolean
  className?: string
  id?: string
}

export function Switch({ 
  checked = false, 
  onCheckedChange, 
  disabled = false,
  className,
  id 
}: SwitchProps) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      id={id}
      disabled={disabled}
      onClick={() => onCheckedChange?.(!checked)}
      className={cn(
        "relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
        checked ? "bg-primary" : "bg-input",
        className
      )}
    >
      <span
        className={cn(
          "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-background shadow ring-0 transition-transform",
          checked ? "translate-x-5" : "translate-x-0"
        )}
      />
    </button>
  )
}

// web/src/lib/components/ui/switch.svelte
<script lang="ts">
  import { cn } from '$lib/utils'

  interface Props {
    checked?: boolean
    onCheckedChange?: (checked: boolean) => void
    disabled?: boolean
    class?: string
    id?: string
  }

  let {
    checked = $bindable(false),
    onCheckedChange,
    disabled = false,
    class: className = '',
    id,
  }: Props = $props()

  function toggle() {
    checked = !checked
    onCheckedChange?.(checked)
  }
</script>

<button
  type="button"
  role="switch"
  aria-checked={checked}
  {id}
  {disabled}
  onclick={toggle}
  class={cn(
    'relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    checked ? 'bg-primary' : 'bg-input',
    className,
  )}
>
  <span
    class={cn(
      'pointer-events-none inline-block h-5 w-5 transform rounded-full bg-background shadow ring-0 transition-transform',
      checked ? 'translate-x-5' : 'translate-x-0',
    )}
  ></span>
</button>
