// frontend/src/app/(auth)/login/page.tsx
"use client"

import * as React from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Eye, EyeOff, Lock, User } from "lucide-react"
import { authApi } from "@/lib/api"

export default function LoginPage() {
  const router = useRouter()
  const [showPassword, setShowPassword] = React.useState(false)
  const [username, setUsername] = React.useState("")
  const [password, setPassword] = React.useState("")
  const [isLoading, setIsLoading] = React.useState(false)
  const [error, setError] = React.useState("")

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError("")

    try {
      const response = await authApi.login(username, password)

      // Tokens are now stored in httpOnly cookies by the backend
      // Store user info in memory only (not localStorage for security)
      sessionStorage.setItem('user', JSON.stringify(response.user))

      // Redirect based on role
      window.location.href = response.user.role === 'creator' ? '/cabinet' : '/dashboard'
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : 'Login failed. Please check your credentials.'
      setError(errorMessage)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary">
            <span className="text-2xl font-bold text-white">T</span>
          </div>
          <CardTitle className="text-2xl">Tibbiyot Texnikumi</CardTitle>
          <CardDescription>
            Moliyaviy tizim - Buxgalteriya paneli
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            {error && (
              <div className="p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
                {error}
              </div>
            )}
            <div className="space-y-2">
              <label className="text-sm font-medium">Foydalanuvchi nomi</label>
              <div className="relative">
                <User className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input
                  type="text"
                  placeholder="Email"
                  className="pl-10"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Parol</label>
              <div className="relative">
                <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input
                  type={showPassword ? "text" : "password"}
                  placeholder="••••••••"
                  className="pl-10 pr-10"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
                <button
                  type="button"
                  className="absolute right-3 top-3 text-muted-foreground hover:text-foreground"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? (
                    <EyeOff className="h-4 w-4" />
                  ) : (
                    <Eye className="h-4 w-4" />
                  )}
                </button>
              </div>
            </div>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? "Kirish..." : "Kirish"}
            </Button>
          </form>
          
          <div className="mt-4 text-center">
            <Link
              href="/forgot-password"
              className="text-sm text-primary hover:underline"
            >
              Parolni unutdingizmi?
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// web/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { auth } from '$lib/stores/auth.svelte'
  import { Eye, EyeOff, Lock, User } from 'lucide-svelte'
  import Card from '$lib/components/ui/card.svelte'
  import CardHeader from '$lib/components/ui/card-header.svelte'
  import CardTitle from '$lib/components/ui/card-title.svelte'
  import CardDescription from '$lib/components/ui/card-description.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import Button from '$lib/components/ui/button.svelte'
  import Input from '$lib/components/ui/input.svelte'

  let username = $state('')
  let password = $state('')
  let showPassword = $state(false)
  let isLoading = $state(false)
  let error = $state('')

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    isLoading = true
    error = ''
    try {
      await auth.login(username, password)
    } catch (err) {
      error = auth.error || "Login xatosi. Qaytadan urinib ko'ring."
    } finally {
      isLoading = false
    }
  }
</script>

<svelte:head>
  <title>Kirish - EduStatus</title>
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
  <Card class="w-full max-w-md">
    <CardHeader class="text-center">
      <div class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary">
        <span class="text-2xl font-bold text-white">E</span>
      </div>
      <CardTitle class="text-2xl">EduStatus</CardTitle>
      <CardDescription>Moliyaviy tizim - Buxgalteriya paneli</CardDescription>
    </CardHeader>
    <CardContent>
      <form onsubmit={handleSubmit} class="space-y-4">
        {#if error}
          <div class="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-600">
            {error}
          </div>
        {/if}

        <div class="space-y-2">
          <label class="text-sm font-medium" for="username">Foydalanuvchi nomi</label>
          <div class="relative">
            <User class="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
            <Input
              id="username"
              type="text"
              placeholder="Email"
              class="pl-10"
              bind:value={username}
              required
            />
          </div>
        </div>

        <div class="space-y-2">
          <label class="text-sm font-medium" for="password">Parol</label>
          <div class="relative">
            <Lock class="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
            <Input
              id="password"
              type={showPassword ? 'text' : 'password'}
              placeholder="••••••••"
              class="pl-10 pr-10"
              bind:value={password}
              required
            />
            <button
              type="button"
              class="absolute right-3 top-3 text-muted-foreground hover:text-foreground"
              onclick={() => (showPassword = !showPassword)}
            >
              {#if showPassword}
                <EyeOff class="h-4 w-4" />
              {:else}
                <Eye class="h-4 w-4" />
              {/if}
            </button>
          </div>
        </div>

        <Button type="submit" class="w-full" disabled={isLoading}>
          {isLoading ? 'Kirish...' : 'Kirish'}
        </Button>
      </form>

      <div class="mt-4 text-center">
        <a href="/forgot-password" class="text-sm text-primary hover:underline">
          Parolni unutdingizmi?
        </a>
      </div>
    </CardContent>
  </Card>
</div>
