// frontend/src/app/dashboard/contracts/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  FileSignature,
  Download,
  Eye,
  Printer,
  CheckCircle,
  Clock,
  AlertTriangle,
} from "lucide-react"
import { formatCurrency, formatDate } from "@/lib/utils"

// Mock data
const contracts = [
  {
    id: "1",
    studentName: "Aliyev Anvar Abdullaevich",
    contractNo: "SH-2025-001",
    amount: 12000000,
    date: "2025-01-10",
    status: "signed",
    signedAt: "2025-01-12",
  },
  {
    id: "2",
    studentName: "Valiyeva Dilnoza Karimovna",
    contractNo: "SH-2025-002",
    amount: 12000000,
    date: "2025-01-10",
    status: "pending",
    signedAt: null,
  },
  {
    id: "3",
    studentName: "Karimov Bobur Rahimovich",
    contractNo: "SH-2025-003",
    amount: 12000000,
    date: "2025-01-08",
    status: "signed",
    signedAt: "2025-01-09",
  },
  {
    id: "4",
    studentName: "Najimova Nigora Bahodirovna",
    contractNo: "SH-2025-004",
    amount: 15000000,
    date: "2025-01-05",
    status: "expired",
    signedAt: null,
  },
  {
    id: "5",
    studentName: "Rahimov Jahongir Toshmatovich",
    contractNo: "SH-2025-005",
    amount: 12000000,
    date: "2025-01-15",
    status: "draft",
    signedAt: null,
  },
]

export default function ContractsPage() {
  const getStatusBadge = (status: string) => {
    switch (status) {
      case "signed":
        return <Badge variant="success">Imzolangan</Badge>
      case "pending":
        return <Badge variant="warning">Kutilmoqda</Badge>
      case "expired":
        return <Badge variant="error">Muddati o'tgan</Badge>
      case "draft":
        return <Badge variant="secondary">Qoralama</Badge>
      default:
        return <Badge>{status}</Badge>
    }
  }

  const signedAmount = contracts
    .filter((c) => c.status === "signed")
    .reduce((sum, c) => sum + c.amount, 0)

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Shartnomalar</h1>
          <p className="text-muted-foreground">
            Avtomatik shartnoma generatsiyasi va boshqaruvi
          </p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Jami shartnomalar</CardTitle>
            <FileSignature className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{contracts.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Imzolangan</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              {contracts.filter((c) => c.status === "signed").length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Imzolangan summa</CardTitle>
            <CheckCircle className="h-4 w-4 text-blue-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">{formatCurrency(signedAmount)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Kutilmoqda</CardTitle>
            <Clock className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">
              {contracts.filter((c) => c.status === "pending").length}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Auto-generation info */}
      <Card className="bg-blue-50 border-blue-200">
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
              <FileSignature className="h-6 w-6 text-blue-600" />
            </div>
            <div>
              <h3 className="font-semibold text-blue-800">Avtomatik generatsiya</h3>
              <p className="text-sm text-blue-600">
                Shartnomalar avtomatik ravishda talaba ma'lumotlari asosida yaratiladi
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Contracts Table */}
      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Shartnoma №</TableHead>
                <TableHead>Talaba</TableHead>
                <TableHead>Summa</TableHead>
                <TableHead>Sana</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Imzolangan</TableHead>
                <TableHead className="text-right">Amallar</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {contracts.map((contract) => (
                <TableRow key={contract.id}>
                  <TableCell className="font-mono">{contract.contractNo}</TableCell>
                  <TableCell className="font-medium">{contract.studentName}</TableCell>
                  <TableCell>{formatCurrency(contract.amount)}</TableCell>
                  <TableCell>{formatDate(contract.date)}</TableCell>
                  <TableCell>{getStatusBadge(contract.status)}</TableCell>
                  <TableCell>{contract.signedAt ? formatDate(contract.signedAt) : "-"}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="sm">
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm">
                        <Download className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm">
                        <Printer className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// web/src/routes/dashboard/hr/contracts/+page.svelte
<script lang="ts">
  import { FileSignature, Plus } from 'lucide-svelte'
  import Badge from '$lib/components/ui/badge.svelte'
  import Card from '$lib/components/ui/card.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import Button from '$lib/components/ui/button.svelte'
  import Table from '$lib/components/ui/table.svelte'
  import TableHeader from '$lib/components/ui/table-header.svelte'
  import TableBody from '$lib/components/ui/table-body.svelte'
  import TableRow from '$lib/components/ui/table-row.svelte'
  import TableHead from '$lib/components/ui/table-head.svelte'
  import TableCell from '$lib/components/ui/table-cell.svelte'

  const contracts = [
    { id: '1', employee: 'Toshmatov Sardor', contractNo: 'IK-2024-001', startDate: '2024-09-01', endDate: '2025-08-31', salary: 5000000, status: 'active' },
    { id: '2', employee: "Xasanova Gulnora", contractNo: 'IK-2024-002', startDate: '2024-09-01', endDate: '2025-08-31', salary: 3500000, status: 'active' },
  ]
</script>

<svelte:head><title>Mehnat shartnomalari - EduStatus</title></svelte:head>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">Mehnat Shartnomalari</h1>
      <p class="text-muted-foreground">Xodimlar mehnat shartnomalari</p>
    </div>
    <Button><Plus class="mr-2 h-4 w-4" />Shartnoma qo'shish</Button>
  </div>
  <Card>
    <CardContent class="pt-6">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Xodim</TableHead>
            <TableHead>Shartnoma №</TableHead>
            <TableHead>Boshlanish</TableHead>
            <TableHead>Tugash</TableHead>
            <TableHead>Maosh</TableHead>
            <TableHead>Status</TableHead>
            <TableHead class="text-right">Amallar</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each contracts as contract}
            <TableRow>
              <TableCell class="font-medium">{contract.employee}</TableCell>
              <TableCell class="font-mono text-sm">{contract.contractNo}</TableCell>
              <TableCell>{contract.startDate}</TableCell>
              <TableCell>{contract.endDate}</TableCell>
              <TableCell>{contract.salary.toLocaleString()} so'm</TableCell>
              <TableCell><Badge variant="success">Faol</Badge></TableCell>
              <TableCell class="text-right"><Button variant="ghost" size="sm">Ko'rish</Button></TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    </CardContent>
  </Card>
</div>
