// frontend/src/app/dashboard/hr/vacations/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Select } from "@/components/ui/select"
import Link from "next/link"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Search, ArrowLeft, Calendar, CheckCircle, Clock } from "lucide-react"

const vacations = [
  { id: "1", employeeName: "Ahmedov Rustam", type: "Yillik", startDate: "2024-07-01", endDate: "2024-07-28", days: 28, status: "approved" },
  { id: "2", employeeName: "Karimova Dilfuza", type: "Yillik", startDate: "2024-08-01", endDate: "2024-08-21", days: 21, status: "pending" },
  { id: "3", employeeName: "Valiyev Bobur", type: "Kasallik", startDate: "2024-06-15", endDate: "2024-06-20", days: 5, status: "approved" },
]

export default function VacationsPage() {
  const [search, setSearch] = useState("")
  const [statusFilter, setStatusFilter] = useState("all")

  const filteredVacations = vacations.filter((v) => {
    const matchesSearch = v.employeeName.toLowerCase().includes(search.toLowerCase())
    const matchesStatus = statusFilter === "all" || v.status === statusFilter
    return matchesSearch && matchesStatus
  })

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "approved":
        return <Badge variant="success">Tasdiqlangan</Badge>
      case "pending":
        return <Badge variant="warning">Kutilmoqda</Badge>
      default:
        return <Badge variant="secondary">{status}</Badge>
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" asChild>
          <Link href="/dashboard/hr">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Orqaga
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold">Ta'tillar</h1>
          <p className="text-muted-foreground">Ta'til arizalari</p>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Jami arizalar</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent><div className="text-2xl font-bold">{vacations.length}</div></CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Tasdiqlangan</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent><div className="text-2xl font-bold text-green-600">{vacations.filter(v => v.status === "approved").length}</div></CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Kutilmoqda</CardTitle>
            <Clock className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent><div className="text-2xl font-bold text-yellow-600">{vacations.filter(v => v.status === "pending").length}</div></CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col gap-4 md:flex-row md:items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Qidirish..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              options={[
                { value: "all", label: "Barcha statuslar" },
                { value: "approved", label: "Tasdiqlangan" },
                { value: "pending", label: "Kutilmoqda" },
              ]}
              className="w-[180px]"
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Xodim</TableHead>
                <TableHead>Turi</TableHead>
                <TableHead>Boshlanish</TableHead>
                <TableHead>Tugash</TableHead>
                <TableHead>Kunlar</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredVacations.map((vacation) => (
                <TableRow key={vacation.id}>
                  <TableCell className="font-medium">{vacation.employeeName}</TableCell>
                  <TableCell>{vacation.type}</TableCell>
                  <TableCell>{new Date(vacation.startDate).toLocaleDateString('uz-UZ')}</TableCell>
                  <TableCell>{new Date(vacation.endDate).toLocaleDateString('uz-UZ')}</TableCell>
                  <TableCell>{vacation.days} kun</TableCell>
                  <TableCell>{getStatusBadge(vacation.status)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

// web/src/routes/dashboard/hr/vacations/+page.svelte
<script lang="ts">
  import { Calendar, Plus } from 'lucide-svelte'
  import Badge from '$lib/components/ui/badge.svelte'
  import Card from '$lib/components/ui/card.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import Button from '$lib/components/ui/button.svelte'
  import Table from '$lib/components/ui/table.svelte'
  import TableHeader from '$lib/components/ui/table-header.svelte'
  import TableBody from '$lib/components/ui/table-body.svelte'
  import TableRow from '$lib/components/ui/table-row.svelte'
  import TableHead from '$lib/components/ui/table-head.svelte'
  import TableCell from '$lib/components/ui/table-cell.svelte'

  const vacations = [
    { id: '1', employee: "Xasanova Gulnora", startDate: '2025-02-10', endDate: '2025-02-21', days: 12, type: "Yillik ta'til", status: 'approved' },
    { id: '2', employee: 'Toshmatov Sardor', startDate: '2025-03-01', endDate: '2025-03-14', days: 14, type: "Yillik ta'til", status: 'pending' },
  ]
</script>

<svelte:head><title>Ta'tillar - EduStatus</title></svelte:head>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">Ta'tillar</h1>
      <p class="text-muted-foreground">Xodimlar ta'til so'rovlari</p>
    </div>
    <Button><Plus class="mr-2 h-4 w-4" />Ta'til so'rash</Button>
  </div>
  <Card>
    <CardContent class="pt-6">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Xodim</TableHead>
            <TableHead>Boshlanish</TableHead>
            <TableHead>Tugash</TableHead>
            <TableHead>Kunlar</TableHead>
            <TableHead>Tur</TableHead>
            <TableHead>Status</TableHead>
            <TableHead class="text-right">Amallar</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each vacations as vac}
            <TableRow>
              <TableCell class="font-medium">{vac.employee}</TableCell>
              <TableCell>{vac.startDate}</TableCell>
              <TableCell>{vac.endDate}</TableCell>
              <TableCell>{vac.days} kun</TableCell>
              <TableCell><Badge variant="secondary">{vac.type}</Badge></TableCell>
              <TableCell>
                {#if vac.status === 'approved'}
                  <Badge variant="success">Tasdiqlandi</Badge>
                {:else}
                  <Badge variant="warning">Kutilmoqda</Badge>
                {/if}
              </TableCell>
              <TableCell class="text-right">
                {#if vac.status === 'pending'}
                  <Button variant="outline" size="sm">Tasdiqlash</Button>
                {:else}
                  <Button variant="ghost" size="sm">Ko'rish</Button>
                {/if}
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    </CardContent>
  </Card>
</div>
