// frontend/src/app/dashboard/reports/page.tsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
  BarChart3,
  Download,
  FileText,
  TrendingUp,
  Users,
  DollarSign,
  Calendar,
} from "lucide-react"
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  Legend,
} from "recharts"
import { formatCurrency } from "@/lib/utils"

// Mock data
const monthlyData = [
  { month: "Sent", revenue: 280000000, students: 310 },
  { month: "Okt", revenue: 310000000, students: 315 },
  { month: "Noy", revenue: 295000000, students: 318 },
  { month: "Dek", revenue: 340000000, students: 320 },
  { month: "Yan", revenue: 325000000, students: 320 },
  { month: "Fev", revenue: 180000000, students: 320 },
]

const reports = [
  { name: "Oylik moliyaviy hisobot", icon: DollarSign, date: "2025-01-15" },
  { name: "Talabalar statistikasi", icon: Users, date: "2025-01-15" },
  { name: "Qarzdorlik hisoboti", icon: TrendingUp, date: "2025-01-14" },
  { name: "To'lovlar hisoboti", icon: FileText, date: "2025-01-14" },
]

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Hisobotlar</h1>
          <p className="text-muted-foreground">
            Moliyaviy va statistik hisobotlar
          </p>
        </div>
        <Button>
          <Download className="mr-2 h-4 w-4" />
          Barchasini yuklab olish
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Yillik tushum</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatCurrency(1730000000)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">O'rtacha oylik</CardTitle>
            <TrendingUp className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">{formatCurrency(288000000)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Jami talabalar</CardTitle>
            <Users className="h-4 w-4 text-blue-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">320</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Hisobotlar soni</CardTitle>
            <FileText className="h-4 w-4 text-purple-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-purple-600">24</div>
          </CardContent>
        </Card>
      </div>

      {/* Charts */}
      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Oylik tushumlar</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis tickFormatter={(value) => `${value / 1000000}M`} />
                  <Tooltip formatter={(value: number) => formatCurrency(value)} />
                  <Area
                    type="monotone"
                    dataKey="revenue"
                    stroke="#3b82f6"
                    fill="#3b82f6"
                    fillOpacity={0.2}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Talabalar soni</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="students" fill="#22c55e" name="Talabalar" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Available Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Mavjud hisobotlar</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {reports.map((report, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded-lg border p-4"
              >
                <div className="flex items-center gap-4">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100">
                    <report.icon className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-medium">{report.name}</p>
                    <p className="text-sm text-muted-foreground">
                      Oxirgi yangilanish: {report.date}
                    </p>
                  </div>
                </div>
                <Button variant="outline" size="sm">
                  <Download className="mr-2 h-4 w-4" />
                  Yuklab olish
                </Button>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// web/src/routes/dashboard/reports/+page.svelte
<script lang="ts">
  import { FileText, Download, TrendingUp } from 'lucide-svelte'
  import { formatCurrency } from '$lib/utils'
  import Card from '$lib/components/ui/card.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import CardHeader from '$lib/components/ui/card-header.svelte'
  import CardTitle from '$lib/components/ui/card-title.svelte'
  import Button from '$lib/components/ui/button.svelte'

  const reports = [
    { id: '1', title: "Oylik to'lov hisoboti", period: '2025 Yanvar', revenue: 45000000 },
    { id: '2', title: 'Qarzdorlik hisoboti', period: '2025 Yanvar', revenue: 12500000 },
    { id: '3', title: "Talabalar statistikasi", period: '2025 Yanvar', revenue: 0 },
  ]
</script>

<svelte:head><title>Hisobotlar - EduStatus</title></svelte:head>

<div class="space-y-6">
  <div>
    <h1 class="text-2xl font-bold tracking-tight">Hisobotlar</h1>
    <p class="text-muted-foreground">Moliyaviy va statistik hisobotlar</p>
  </div>

  <div class="grid gap-4 md:grid-cols-3">
    {#each reports as report}
      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium">{report.title}</CardTitle>
          <FileText class="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div class="text-xl font-bold">{report.period}</div>
          {#if report.revenue > 0}
            <p class="text-sm text-muted-foreground">{formatCurrency(report.revenue)}</p>
          {/if}
          <Button variant="outline" size="sm" class="mt-3 w-full">
            <Download class="mr-2 h-4 w-4" />
            Yuklab olish
          </Button>
        </CardContent>
      </Card>
    {/each}
  </div>

  <Card>
    <CardHeader>
      <CardTitle>Yillik ko'rsatkichlar</CardTitle>
    </CardHeader>
    <CardContent>
      <div class="flex h-64 items-center justify-center text-muted-foreground">
        <div class="text-center">
          <TrendingUp class="h-12 w-12 mx-auto mb-2" />
          <p>Grafik tez orada qo'shiladi</p>
        </div>
      </div>
    </CardContent>
  </Card>
</div>
