// frontend/src/app/cabinet/organization/page.tsx
/**
 * Organization List Page
 * 
 * Main page for viewing and managing organizations list.
 * Refactored to follow Single Responsibility Principle:
 * - Constants moved to lib/constants/organization-list.ts
 * - Types moved to types/organization.ts
 * - Logic moved to useOrganizationList hook
 * - Utils imported from lib/utils/organization.ts
 */

"use client"

import { useState } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Search,
  Plus,
  Filter,
  Eye,
  Globe,
  Users,
  TrendingUp,
  AlertTriangle,
  Building2,
} from "lucide-react"
import Link from "next/link"

// Hooks
import { useAuth } from "@/lib/auth-context"
import { useOrganizationList } from "@/lib/hooks/useOrganizationList"

// Components
import { AddOrganizationModal } from "./components/AddOrganizationModal"

// Constants
import {
  PLAN_COLORS,
  STATUS_COLORS,
  STATUS_LABELS,
  PLAN_FILTER_OPTIONS,
  STATUS_FILTER_OPTIONS,
} from "@/lib/constants/organization-list"

// Utils
import { formatInn, getDisplayDomain } from "@/lib/utils/organization"

/**
 * Organization List Page Component
 */
export default function OrganizationPage() {
  const { token } = useAuth()

  // --- Data Hook ---
  const {
    organizations,
    loading,
    error,
    filters,
    stats,
    filteredOrganizations,
    setSearch,
    setPlanFilter,
    setStatusFilter,
    reload,
  } = useOrganizationList(token)

  // --- Modal State ---
  const [isModalOpen, setIsModalOpen] = useState(false)

  // --- Callbacks ---
  const handleOpenModal = () => setIsModalOpen(true)
  const handleCloseModal = () => setIsModalOpen(false)
  const handleSuccess = async () => await reload()

  // --- Early Returns ---
  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600"></div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="p-6">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
          {error}
        </div>
      </div>
    )
  }

  // --- Render ---
  return (
    <>
      <div className="space-y-6">
        {/* Page Header */}
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Tashkilotlar</h1>
            <p className="text-muted-foreground">
              Barcha tashkilotlar ro'yxati va ularning holati
            </p>
          </div>
          <Button onClick={handleOpenModal}>
            <Plus className="mr-2 h-4 w-4" />
            Yangi tashkilot qo'shish
          </Button>
        </div>

        {/* Stats Cards */}
        <StatsCards stats={stats} />

        {/* Filters */}
        <FiltersCard
          search={filters.search}
          planFilter={filters.plan}
          statusFilter={filters.status}
          onSearchChange={setSearch}
          onPlanChange={setPlanFilter}
          onStatusChange={setStatusFilter}
        />

        {/* Organizations Table */}
        <OrganizationsTable organizations={filteredOrganizations} />

        {/* Pagination Info */}
        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Jami: {filteredOrganizations.length} ta tashkilot
          </p>
        </div>
      </div>

      {/* Add Organization Modal */}
      <AddOrganizationModal
        isOpen={isModalOpen}
        onClose={handleCloseModal}
        token={token!}
        organizations={organizations}
        onSuccess={handleSuccess}
      />
    </>
  )
}

/**
 * Stats Cards Component
 */
interface StatsCardsProps {
  stats: {
    total: number
    active: number
    trial: number
    suspended: number
    totalStudents: number
  }
}

function StatsCards({ stats }: StatsCardsProps) {
  return (
    <div className="grid gap-4 md:grid-cols-4">
      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-purple-100">
              <Globe className="h-5 w-5 text-purple-600" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Jami tashkilotlar</p>
              <p className="text-xl font-bold">{stats.total}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100">
              <TrendingUp className="h-5 w-5 text-green-600" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Faol</p>
              <p className="text-xl font-bold text-green-600">{stats.active}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-yellow-100">
              <AlertTriangle className="h-5 w-5 text-yellow-600" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Sinov / To'xtatilgan</p>
              <p className="text-xl font-bold text-yellow-600">
                {stats.trial} / {stats.suspended}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100">
              <Users className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Jami talabalar</p>
              <p className="text-xl font-bold">{stats.totalStudents.toLocaleString()}</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

/**
 * Filters Card Component
 */
interface FiltersCardProps {
  search: string
  planFilter: string
  statusFilter: string
  onSearchChange: (value: string) => void
  onPlanChange: (value: string) => void
  onStatusChange: (value: string) => void
}

function FiltersCard({
  search,
  planFilter,
  statusFilter,
  onSearchChange,
  onPlanChange,
  onStatusChange,
}: FiltersCardProps) {
  return (
    <Card>
      <CardContent className="pt-6">
        <div className="flex flex-col gap-4 md:flex-row">
          <div className="relative flex-1">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Nomi, subdomain yoki email bo'yicha qidirish..."
              className="pl-8"
              value={search}
              onChange={(e) => onSearchChange(e.target.value)}
            />
          </div>
          <select
            className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 md:w-[150px]"
            value={planFilter}
            onChange={(e) => onPlanChange(e.target.value)}
          >
            {PLAN_FILTER_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <select
            className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 md:w-[150px]"
            value={statusFilter}
            onChange={(e) => onStatusChange(e.target.value)}
          >
            {STATUS_FILTER_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <Button variant="outline" size="icon">
            <Filter className="h-4 w-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

/**
 * Organizations Table Component
 */
import type { Organization } from "@/types/organization"

interface OrganizationsTableProps {
  organizations: Organization[]
}

function OrganizationsTable({ organizations }: OrganizationsTableProps) {
  if (organizations.length === 0) {
    return (
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Tashkilot</TableHead>
                <TableHead>INN</TableHead>
                <TableHead>Domain</TableHead>
                <TableHead>Tarif</TableHead>
                <TableHead>Talabalar</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="w-[100px]">Amallar</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell colSpan={7} className="text-center text-muted-foreground py-8">
                  Tashkilotlar topilmadi
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Tashkilot</TableHead>
              <TableHead>INN</TableHead>
              <TableHead>Domain</TableHead>
              <TableHead>Tarif</TableHead>
              <TableHead>Talabalar</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="w-[100px]">Amallar</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {organizations.map((org) => (
              <OrganizationRow key={org.id} organization={org} />
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}

/**
 * Organization Row Component
 */
function OrganizationRow({ organization }: { organization: Organization }) {
  return (
    <TableRow>
      <TableCell>
        <div className="flex items-center gap-3">
          {organization.logo ? (
            <img
              src={organization.logo}
              alt={organization.name}
              className="h-10 w-10 rounded-lg object-cover border"
            />
          ) : (
            <div className="h-10 w-10 rounded-lg bg-purple-100 flex items-center justify-center border">
              <Building2 className="h-5 w-5 text-purple-600" />
            </div>
          )}
          <div>
            <p className="font-medium">{organization.name}</p>
            <p className="text-sm text-muted-foreground">{organization.phone}</p>
          </div>
        </div>
      </TableCell>
      <TableCell>
        <span className="font-mono text-sm">{formatInn(organization.inn)}</span>
      </TableCell>
      <TableCell>
        <div className="flex items-center gap-2">
          <Globe className="h-4 w-4 text-muted-foreground" />
          <span className="text-sm">{getDisplayDomain(organization)}</span>
        </div>
      </TableCell>
      <TableCell>
        <Badge variant={PLAN_COLORS[organization.plan] as "outline" | "secondary" | "default"}>
          {organization.plan.toUpperCase()}
        </Badge>
      </TableCell>
      <TableCell>{organization._count?.students || 0}</TableCell>
      <TableCell>
        <Badge variant={STATUS_COLORS[organization.status]}>
          {STATUS_LABELS[organization.status]}
        </Badge>
      </TableCell>
      <TableCell>
        <Link href={`/cabinet/organization/${organization.id}`}>
          <Button variant="ghost" size="icon" title="Ko'rish">
            <Eye className="h-4 w-4" />
          </Button>
        </Link>
      </TableCell>
    </TableRow>
  )
}

// web/src/routes/cabinet/organization/+page.svelte
<script lang="ts">
  import { Building2, Plus, Search } from 'lucide-svelte'
  import Badge from '$lib/components/ui/badge.svelte'
  import Card from '$lib/components/ui/card.svelte'
  import CardContent from '$lib/components/ui/card-content.svelte'
  import Button from '$lib/components/ui/button.svelte'
  import Input from '$lib/components/ui/input.svelte'
  import Table from '$lib/components/ui/table.svelte'
  import TableHeader from '$lib/components/ui/table-header.svelte'
  import TableBody from '$lib/components/ui/table-body.svelte'
  import TableRow from '$lib/components/ui/table-row.svelte'
  import TableHead from '$lib/components/ui/table-head.svelte'
  import TableCell from '$lib/components/ui/table-cell.svelte'

  const organizations = [
    { id: '1', name: 'Tibbiyot Texnikumi', inn: '123456789', phone: '+998901111111', plan: 'pro', status: 'active', clients: 320, createdAt: '2024-09-01' },
    { id: '2', name: 'IT Academy', inn: '987654321', phone: '+998902222222', plan: 'basic', status: 'trial', clients: 150, createdAt: '2024-11-15' },
  ]

  let search = $state('')
  const filtered = $derived(organizations.filter((o) => o.name.toLowerCase().includes(search.toLowerCase())))
</script>

<svelte:head><title>Tashkilotlar - Cabinet</title></svelte:head>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">Tashkilotlar</h1>
      <p class="text-muted-foreground">Barcha tashkilotlarni boshqarish</p>
    </div>
    <Button><Plus class="mr-2 h-4 w-4" />Yangi tashkilot</Button>
  </div>

  <Card>
    <CardContent class="pt-6">
      <div class="flex gap-4 mb-4">
        <div class="relative flex-1">
          <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input placeholder="Tashkilot nomi bo'yicha qidirish..." bind:value={search} class="pl-10" />
        </div>
      </div>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Nom</TableHead>
            <TableHead>INN</TableHead>
            <TableHead>Telefon</TableHead>
            <TableHead>Tarif</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Mijozlar</TableHead>
            <TableHead class="text-right">Amallar</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each filtered as org}
            <TableRow>
              <TableCell class="font-medium">{org.name}</TableCell>
              <TableCell class="font-mono text-sm">{org.inn}</TableCell>
              <TableCell>{org.phone}</TableCell>
              <TableCell class="capitalize">{org.plan}</TableCell>
              <TableCell>
                {#if org.status === 'active'}
                  <Badge variant="success">Faol</Badge>
                {:else}
                  <Badge variant="warning">Sinov</Badge>
                {/if}
              </TableCell>
              <TableCell>{org.clients}</TableCell>
              <TableCell class="text-right">
                <a href="/cabinet/organization/{org.id}">
                  <Button variant="ghost" size="sm">Ko'rish</Button>
                </a>
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    </CardContent>
  </Card>
</div>
